# Importe NumPy como np 
# Crie um array de 10 zeros
# Crie um array de inteiros de 10 até 50
# Crie um array dos números pares de 10 até 50
# Crie uma matriz 3x3 com valores variando de 0 até 8
# Opcional :
# Use NumPy para gerar números inteiros aleatórios entre 0 e 10
# Use Numpy para gerar um array de 25 números aleatórios.



In [1]:
# Importe NumPy como np
import numpy as np

In [4]:
# Crie um array de 10 zeros
lista = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
lista

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [8]:
#Crie um array de inteiros de 10 até 50
lista = np.arange(10,51)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
# Criei uma matriz 3x3 com valores variando de 0 até 8
lista = np.arange(10,51,2)
lista

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
# Crie uma matriz 3x3 com valores variando de 0 até 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
import random

In [40]:
# Use NumPy para gerar números inteiros aleatórios entre 0 e 10
x = np.arange(0,9)
random.shuffle(x)
x

array([8, 1, 2, 0, 3, 6, 7, 5, 4])

In [43]:
# Use NumPy para gerar números inteiros aleatórios entre 0 e 10
np.random.randint(0,10)

2

In [47]:
# Use Numpy para gerar um array de 25 números aleatórios.
y = np.arange(25)
random.shuffle(y)
y

array([17, 24,  9,  0,  1, 23,  3, 12, 15,  7, 13, 14,  6, 16, 22,  5,  2,
       18, 19, 11,  4, 20, 10,  8, 21])

In [45]:
# Use Numpy para gerar um array de 25 números aleatórios.
np.random.randint(1,1000,25)

array([ 51, 574, 235, 747, 730, 371, 529, 866, 926,  93, 321, 346, 331,
       780, 295, 598, 337, 779, 838, 705, 269, 663, 513, 890, 545])