In [15]:
# importei a blibioteca de tempo
import time
inicio = time.time() #tempo atual
lista1 = range(10000000)
lista2 = range(10000000)
lista3 = []
for i in range(len(lista1)):
    lista3.append(lista1[i] + lista2[i])
tempo_gasto = time.time() - inicio
tempo_gasto

7.189242839813232

In [20]:
import numpy as np
inicio = time.time()
lista1 = np.arange(10000000)
lista2 = np.arange(10000000)
lista3 = lista1 + lista2
tempo_gasto = time.time() - inicio
tempo_gasto

0.19146180152893066

# Exemplos de uso numpy

In [ ]:
import numpy as np

In [21]:
lista = np.arange(5)
lista

array([0, 1, 2, 3, 4])

In [22]:
import numpy as np
lista = np.arange(1,6)
lista

array([1, 2, 3, 4, 5])

In [24]:
lista = np.arange(1,10,2)
lista

array([1, 3, 5, 7, 9])

In [26]:
lista = np.arange(10,0,-1)
lista

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
lista = np.arange(0,5,2)
lista

array([0, 2, 4])

In [31]:
lista = np.arange(0,1.1,0.1)
lista

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Outras aplicações com array de numpy

In [32]:
lista = np.array([2,5,99])
lista

array([ 2,  5, 99])

In [80]:
linha1 = [1,2,3]
linha2 = [5,4,3]
linha3 = [6,7,8]

lista_bidimensional = np.array([linha1,linha2,linha3])
lista_bidimensional

array([[1, 2, 3],
       [5, 4, 3],
       [6, 7, 8]])

In [60]:
lista_bidimensional[0][2]

3

In [43]:
np.arange(15).reshape(3,5) #o rechape transformou o veror(15), em uma matriz (3,5)-[3 linhas e 5 colunas]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
lista_bidimensional.shape # quantidade de linhas e colunas

(3, 3)

In [45]:
lista_bidimensional.dtype.name # Tipo dos elementos (são números inteiros e 32byte é a quantidade de memoria que é usado)

'int32'

In [46]:
lista_bidimensional.size # quantidade de elementos

9

In [62]:
lista_depython = [1,5,9]
#lista_de_python + 1 da errado
lista_de_numpy = np.array([1,5,9])
lista_de_numpy + 1

array([ 2,  6, 10])

In [74]:
lista_bidimensional

array([[1, 2, 3],
       [5, 4, 3],
       [6, 7, 8]])

In [81]:
lista_bidimensional[2][1] = lista_bidimensional[2][1] + 3 # cada vez executar, ele vai armazenar e somar +3

In [82]:
lista_bidimensional

array([[ 1,  2,  3],
       [ 5,  4,  3],
       [ 6, 10,  8]])

In [89]:
array2 = np.array([[1,1,1],[2,2,2],[5,5,5]]) # 2 conchetes é pq são 2 dimenções
array2

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

In [90]:
array2 + lista_bidimensional  # somei 2 matrizes

array([[ 2,  3,  4],
       [ 7,  6,  5],
       [11, 15, 13]])