In [1]:
# importei a biblioteca de tempo
import time
# usei a função time para adquirir o horario atual do computador
inicio = time.time()
# gerei duas listas com 10000000 valores
lista1 = range(10000000)
lista2 = range(10000000)
lista3 = []
# usei um for para somar cada item das listas e salvo o resultado na lista3
for i in range(len(lista1)):
    lista3.append(lista1[i] + lista2[i])
# tempo_gasto é o horario atual menos o horario quando comecei
tempo_gasto = time.time() - inicio
# colocar apenas a variavel imprime o valor dela
tempo_gasto

13.761359930038452

In [2]:
# agora vou usar a biblioteca externa numpy
# quando uso o "as" posso dar um apelido a minha biblioteca
# entao fazendo "import numpy as np" posso usar np ao inves de escrever numpy
import numpy as np
inicio = time.time()
lista1 = np.arange(10000000)
lista2 = np.arange(10000000)
# Na hora de somar as listas de tamanho igual posso fazer a operação sem precisar do for
lista3 = lista1 + lista2
tempo_gasto = time.time() - inicio
tempo_gasto # e ainda gasto menos tempo

0.4007148742675781

# Exemplos de uso do numpy

In [3]:
import numpy as np #Antes de usar qualquer coisa do numpy preciso importar a biblioteca antes.
# so preciso importar 1 vez por notebook
# É uma boa prática deixar os imports de bibliotecas, internas ou externas, em uma celula separada

In [4]:
# arange cria um array com espaçamentos iguais
# começa no 0, vai até antes do elemento passado, 15 nesse exemplo, indo de 1 a 1.
# start, stop, step
lista = np.arange(15)
lista

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# O padrão é começar pelo 0, mas posso passar outro valor para o começo
# Nesse exemplo começo do 1 e vou até antes do 6
lista = np.arange(1,6)
lista

array([1, 2, 3, 4, 5])

In [6]:
# Posso também mudar o ritmo da mudança, o step.
# Nesse caso quero ir de 1 até antes do 10, de 2 em 2
lista = np.arange(1,10,2)
lista

array([1, 3, 5, 7, 9])

In [7]:
# Se o step for negativo, podemos fazer sequencias decrescentes
lista = np.arange(10,0,-1)
lista

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [8]:
# Outro exemplo começando em 0, indo de 2 em 2 até antes do 5
lista = np.arange(0,5,2)
lista

array([0, 2, 4])

In [9]:
# Outro exemplo começando em 0, indo de 0.1 em 0.1 até antes do 1.1
lista = np.arange(0,1.1,0.1)
lista

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Outras aplicações com array de numpy

In [10]:
# temos também a função array, para atribuir valores não sequenciais
lista = np.array([2,5,99])
lista

array([ 2,  5, 99])

In [11]:
# Com essa função podemos trabalhar com arrays (listas/matrizes/vetores) bidimensionais
# Ou seja basicamente uma planilha com linhas e colunas
# aqui eu crio um array com 3 linhas. Onde a primeira é 1,2,3 a segunda 5,4,3 e a terceira 6,7,8
linha1 = [1,2,3]
linha2 = [5,4,3]
linha3 = [6,7,8]
# Importante notar que ao usar a função array de numpy precisamos:
# 1. abrir os parenteses, já que array é uma função -- np.array()
# 2. Abrir os corchetes, já que ele vai ter linhas e colunas -- np.array([])
# 3. Dentro dos corchetes adicionamos as linhas de mesmo tamanho -- np.array([linha1, linha2, linha3])
lista_bidimensional = np.array([linha1, linha2, linha3])
# Seria a mesma coisa se tivessemos feito:
# lista_bidimensional = np.array([[1,2,3],[5,4,3],[6,7,8]])
lista_bidimensional

array([[1, 2, 3],
       [5, 4, 3],
       [6, 7, 8]])

In [12]:
#Para acessar um elemento dessa lista preciso informar a linha e a coluna
#Nesse caso na linha 0 e coluna 2, temos o elemento 3
lista_bidimensional[0][2]

3

In [13]:
# com reshape podemos transformar um array de uma linha só em varias linhas e colunas
# Contanto que o numero de linhas vezes a quantidade de colunas seja igual ao numero de elementos
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
lista_bidimensional.shape # quantidade de linhas e colunas

(3, 3)

In [15]:
lista_bidimensional.dtype.name # Tipo dos elementos

'int32'

In [16]:
lista_bidimensional.size #quantidade de elementos

9

In [17]:
lista_de_python = [1,5,9]
# lista_de_python + 1 da errado
lista_de_numpy = np.array([1,5,9])
lista_de_numpy + 1 # Com numpy somamos 1 a todos os itens da lista (array)

array([ 2,  6, 10])

In [18]:
lista_bidimensional + 1 # Podemos também somar 1 a todos os elementos de uma lista bidimensional
# Importante relembrar que isso vale para qualquer operação aritmetica. Subtração, mutiplicação, divisão...

array([[2, 3, 4],
       [6, 5, 4],
       [7, 8, 9]])

In [19]:
# Sobre a importancia do "igual" ou atribuição;
# Se acessamos um elemento da lista_bidimencional. Linha 2 coluna 1, tem o valor 7
lista_bidimensional[2][1]

7

In [20]:
# Se somamos 3 a esse valor vamos obter 10
lista_bidimensional[2][1] + 3

10

In [21]:
#Porém o valor armazenado em lista_bidimensional continua 7
lista_bidimensional

array([[1, 2, 3],
       [5, 4, 3],
       [6, 7, 8]])

In [22]:
# Precisamos fazer uma atribuição, usar o igual, para salvar a soma na variavel
# E dessa forma modificar a nossa lista_bidimensional:
lista_bidimensional[2][1] = lista_bidimensional[2][1] + 3
lista_bidimensional

array([[ 1,  2,  3],
       [ 5,  4,  3],
       [ 6, 10,  8]])

In [23]:
array2 = np.array([[1,1,1],[2,2,2],[5,5,5]])
array2

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

In [24]:
# Podemos somar dois arrays com as mesmas dimensões (quantidade de linhas e colunas)
# Cada elemento vai somar com sua contraparte
array2 + lista_bidimensional
# de novo, podemos fazer qualquer operação aritmética

array([[ 2,  3,  4],
       [ 7,  6,  5],
       [11, 15, 13]])